name = "BackgammonNet"
uuid = "11d55574-5027-10f8-1967-3b41d663c34d"
version = "0.2.7"
authors = ["sile16@gmail.com"]

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
PyCall = "1.96.4"
StaticArrays = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
